# Generated by Django 3.0.8 on 2020-07-20 22:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 20, 22, 50, 11, 924689, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='address',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='business',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='name',
            field=models.ForeignKey(default='2', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='phone',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='PersonComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('perpetrator', models.CharField(max_length=300)),
                ('job_phone', models.CharField(max_length=200)),
                ('job_email', models.EmailField(max_length=254)),
                ('job', models.CharField(max_length=300)),
                ('social_media', models.CharField(max_length=400)),
                ('review', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 7, 20, 22, 50, 11, 926014, tzinfo=utc))),
                ('name', models.ForeignKey(default='2', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
