# Generated by Django 3.0.8 on 2020-07-18 23:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0008_auto_20200718_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 23, 50, 20, 56975, tzinfo=utc)),
        ),
    ]
