# Generated by Django 3.0.8 on 2020-07-19 02:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0012_auto_20200719_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 2, 13, 51, 931776, tzinfo=utc)),
        ),
    ]
