# Generated by Django 3.0.8 on 2020-07-19 22:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0014_auto_20200719_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 22, 22, 58, 501038, tzinfo=utc)),
        ),
    ]
