# Generated by Django 3.0.7 on 2020-07-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('hatched_on', models.DateTimeField()),
                ('cost_in_dollars', models.FloatField()),
                ('slug', models.SlugField(max_length=128, unique=True)),
            ],
        ),
    ]
