# Generated by Django 3.0.7 on 2020-07-01 03:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snakes_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snake',
            name='slug',
        ),
        migrations.AddField(
            model_name='snake',
            name='feeding_on',
            field=models.CharField(choices=[('LFR', 'Live Fuzzy Rat'), ('LPR', 'Live Pup Rat'), ('LWR', 'Live Weanling Rat'), ('LSR', 'Live Small Rat'), ('FSM', 'F/T Fuzzy Rat'), ('FWR', 'F/T Weanling Rat'), ('FPR', 'F/T Pup Rat'), ('FSR', 'F/T Small Rat')], default='LFR', max_length=3),
        ),
        migrations.AddField(
            model_name='snake',
            name='picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snake',
            name='weighed_on',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snake',
            name='weight',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='snake',
            name='hatched_on',
            field=models.DateField(),
        ),
    ]
