# Generated by Django 3.0.7 on 2020-07-02 02:42

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakes_app', '0003_auto_20200702_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snake',
            name='picture',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='snakes_app/media/photos'), upload_to=''),
        ),
    ]
