# Generated by Django 3.0.8 on 2020-07-09 03:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 7, 9, 3, 41, 47, 273278, tzinfo=utc))),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('fist', models.IntegerField()),
                ('haha', models.IntegerField()),
                ('angry', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
