# Generated by Django 3.0.8 on 2020-07-18 03:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200718_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 3, 44, 22, 612458, tzinfo=utc)),
        ),
    ]
