# Generated by Django 3.0.8 on 2020-07-18 22:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200718_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 22, 33, 52, 321084, tzinfo=utc)),
        ),
    ]
