# Generated by Django 3.0.8 on 2020-07-18 23:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20200718_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 23, 31, 0, 216509, tzinfo=utc)),
        ),
    ]
