# Generated by Django 3.0.8 on 2020-07-20 17:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20200719_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 20, 17, 27, 30, 137108, tzinfo=utc)),
        ),
    ]
