# Generated by Django 3.0.7 on 2020-06-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_code', models.CharField(max_length=100)),
                ('second_code', models.CharField(max_length=100)),
            ],
        ),
    ]
