# Generated by Django 3.0.7 on 2020-06-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='description_text',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
