# Generated by Django 3.0.8 on 2020-07-09 02:31

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BallPython',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('weight', models.FloatField(default=100)),
                ('weighed_on', models.DateField()),
                ('feeding_on', models.CharField(choices=[('LFR', 'Live Fuzzy Rat'), ('LPR', 'Live Pup Rat'), ('LWR', 'Live Weanling Rat'), ('LSR', 'Live Small Rat'), ('FSM', 'F/T Fuzzy Rat'), ('FWR', 'F/T Weanling Rat'), ('FPR', 'F/T Pup Rat'), ('FSR', 'F/T Small Rat')], default='LFR', max_length=3)),
                ('hatched_on', models.DateField()),
                ('cost_in_dollars', models.FloatField()),
                ('picture', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='ball_pythons/media/img'), upload_to='')),
            ],
        ),
    ]
