# Generated by Django 3.0.8 on 2020-07-09 03:00

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ball_pythons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballpython',
            name='picture',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/ball_pythons/img'), upload_to=''),
        ),
    ]
