# Generated by Django 3.0.8 on 2020-07-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ball_pythons', '0004_auto_20200709_0355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genetics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.CharField(max_length=128)),
            ],
        ),
    ]
