# Generated by Django 3.0.8 on 2020-07-14 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ball_pythons', '0005_genetics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genetics',
            new_name='Genetic',
        ),
    ]
