# Generated by Django 3.0.8 on 2020-07-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ball_pythons', '0006_auto_20200714_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballpython',
            name='morph',
            field=models.ManyToManyField(to='ball_pythons.Genetic'),
        ),
    ]
