# Generated by Django 3.0.8 on 2020-07-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ball_pythons', '0007_ballpython_morph'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballpython',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ballpython',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ballpython',
            name='morph',
            field=models.ManyToManyField(related_name='ballpythons', to='ball_pythons.Genetic'),
        ),
    ]
