# Generated by Django 3.0.8 on 2020-07-22 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ball_pythons', '0008_auto_20200717_0317'),
        ('ball_pythons', '0008_auto_20200714_0409'),
    ]

    operations = [
    ]
