# Generated by Django 3.0.7 on 2020-06-25 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='short_url',
            new_name='tiny_url',
        ),
    ]
