# Generated by Django 3.0.7 on 2020-07-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vineyard',
            name='homepage',
            field=models.CharField(default='abc', max_length=250),
            preserve_default=False,
        ),
    ]
