# Generated by Django 3.0.7 on 2020-06-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_text', models.CharField(max_length=150)),
                ('create_date', models.DateField(verbose_name='date started')),
                ('complete_date', models.DateField(verbose_name='date completed')),
                ('completed_bool', models.BooleanField(default=False)),
            ],
        ),
    ]
