# Generated by Django 3.0.7 on 2020-06-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitems',
            name='complete_date',
            field=models.DateField(blank=True, null=True, verbose_name='date completed'),
        ),
        migrations.AlterField(
            model_name='todoitems',
            name='create_date',
            field=models.DateField(auto_now=True, verbose_name='date started'),
        ),
    ]
