# Generated by Django 3.0.7 on 2020-06-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=128)),
                ('artist_name', models.CharField(max_length=128)),
                ('release_year', models.IntegerField()),
                ('spotify_link', models.URLField()),
                ('chords_link', models.URLField()),
                ('info_link', models.URLField()),
            ],
        ),
    ]
