# Generated by Django 3.0.7 on 2020-07-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='chords_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='info_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='release_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='spotify_link',
            field=models.URLField(null=True),
        ),
    ]
