# Generated by Django 3.0.7 on 2020-07-03 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capstone', '0002_auto_20200702_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(blank=True, choices=[('bls', 'Blues'), ('cls', 'Classical/Art'), ('ctr', 'Country'), ('eas', 'Easy Listening'), ('elc', 'Electronic'), ('flk', 'Folk'), ('gos', 'Gospel/Soul'), ('hip', 'Hip-hop/Rap'), ('ins', 'Instrumental'), ('jzz', 'Jazz'), ('ltn', 'Latin'), ('mtl', 'Metal'), ('brd', 'Musical/Broadway'), ('pop', 'General Pop'), ('r&b', 'Rhythm and Blues'), ('reg', 'Reggae'), ('rck', 'Rock'), ('wrl', 'World Music'), ('oth', 'Other')], max_length=20, null=True)),
                ('mode', models.CharField(blank=True, choices=[('MJ', 'Major'), ('mn', 'Minor'), ('Ot', 'Other')], max_length=5, null=True)),
                ('tempo', models.IntegerField(blank=True, null=True)),
                ('singability', models.IntegerField(blank=True, null=True)),
                ('playability', models.IntegerField(blank=True, null=True)),
                ('repetition', models.IntegerField(blank=True, null=True)),
                ('dynamics', models.IntegerField(blank=True, null=True)),
                ('arousal', models.IntegerField(blank=True, null=True)),
                ('popularity', models.IntegerField(blank=True, null=True)),
                ('valence', models.IntegerField(blank=True, null=True)),
                ('emotion', models.CharField(blank=True, max_length=50, null=True)),
                ('theme', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist_name',
        ),
        migrations.AlterField(
            model_name='song',
            name='chords_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='info_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='spotify_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SongReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='capstone.Song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(to='capstone.Artist'),
        ),
    ]
