# Generated by Django 3.0.7 on 2020-07-08 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_auto_20200703_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='chords_link',
        ),
        migrations.RemoveField(
            model_name='song',
            name='info_link',
        ),
        migrations.RemoveField(
            model_name='song',
            name='spotify_link',
        ),
        migrations.RemoveField(
            model_name='songreview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='arousal',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='dynamics',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='emotion',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='playability',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='popularity',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='repetition',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='singability',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='tempo',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='valence',
        ),
        migrations.AddField(
            model_name='song',
            name='arousal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='comments',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='playability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='popularity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='repetition',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='singability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='tempo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='valence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='songreview',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='capstone.Tags'),
            preserve_default=False,
        ),
    ]
