# Generated by Django 3.0.8 on 2020-07-11 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_auto_20200708_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='songs', to='capstone.Quality')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewAvg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('count', models.IntegerField()),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews_avgs', to='capstone.Quality')),
            ],
        ),
        migrations.RemoveField(
            model_name='songreview',
            name='song',
        ),
        migrations.RemoveField(
            model_name='songreview',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='song',
            name='arousal',
        ),
        migrations.RemoveField(
            model_name='song',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='song',
            name='playability',
        ),
        migrations.RemoveField(
            model_name='song',
            name='popularity',
        ),
        migrations.RemoveField(
            model_name='song',
            name='release_year',
        ),
        migrations.RemoveField(
            model_name='song',
            name='repetition',
        ),
        migrations.RemoveField(
            model_name='song',
            name='singability',
        ),
        migrations.RemoveField(
            model_name='song',
            name='tempo',
        ),
        migrations.RemoveField(
            model_name='song',
            name='valence',
        ),
        migrations.AddField(
            model_name='song',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='SongReview',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.AddField(
            model_name='reviewavg',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews_avgs', to='capstone.Song'),
        ),
        migrations.AddField(
            model_name='review',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='songs', to='capstone.Song'),
        ),
        migrations.AddField(
            model_name='comment',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='capstone.Song'),
        ),
        migrations.AddField(
            model_name='song',
            name='highest_avg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='songs', to='capstone.ReviewAvg'),
        ),
    ]
