# Generated by Django 3.0.8 on 2020-07-15 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0006_auto_20200714_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewavg',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='reviewavg',
            name='song',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='score',
            new_name='tempo',
        ),
        migrations.RemoveField(
            model_name='review',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='song',
            name='highest_avg',
        ),
        migrations.RemoveField(
            model_name='song',
            name='year',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Quality',
        ),
        migrations.DeleteModel(
            name='ReviewAvg',
        ),
    ]
