# Generated by Django 3.0.8 on 2020-07-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0009_auto_20200716_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='genre',
            field=models.ManyToManyField(to='capstone.Genre'),
        ),
    ]
