# Generated by Django 3.0.7 on 2020-07-11 03:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope_app', '0002_auto_20200630_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='lower_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sign',
            name='upper_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
