# Generated by Django 3.0.7 on 2020-06-13 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links_app.Link')),
            ],
        ),
    ]
