# Generated by Django 3.0.7 on 2020-06-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemComplete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_complete', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='date created')),
                ('complete_date', models.DateTimeField(verbose_name='date completed')),
            ],
        ),
    ]
