# Generated by Django 3.0.7 on 2020-07-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=8, unique=True)),
                ('full', models.CharField(max_length=240)),
            ],
        ),
    ]
