# Generated by Django 3.0.7 on 2020-06-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mod', models.DateTimeField(auto_now=True)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
    ]
